#!/sbin/openrc-run

name=$RC_SVCNAME
description="mill-box service"
supervisor="supervise-daemon"
command="/usr/bin/mill-box"
extra_commands="checkconfig"
extra_started_commands="reload"

: ${MILLBOX_CONFIG:=${config:-"/etc/mill-box"}}

if [ -d "$MILLBOX_CONFIG" ]; then
	_config_opt="-C $MILLBOX_CONFIG"
elif [ -z "$MILLBOX_CONFIG" ]; then
	_config_opt=""
else
	_config_opt="-c $MILLBOX_CONFIG"
fi

_workdir=${MILLBOX_WORKDIR:-${workdir:-"/var/lib/mill-box"}}

command_args="run --disable-color
	-D $_workdir
	$_config_opt"

depend() {
	after net dns
}

checkconfig() {
	ebegin "Checking $RC_SVCNAME configuration"
	mill-box check -D "$_workdir" $_config_opt
	eend $?
}

start_pre() {
	checkconfig
}

reload() {
	ebegin "Reloading $RC_SVCNAME"
	checkconfig && $supervisor "$RC_SVCNAME" --signal HUP
	eend $?
}
